# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

#  Copy the current directory contents into the container at /app
COPY . /app

# Install the required Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# SExpose the port that Flask runs on
EXPOSE 5000

# Define the command to run your application
CMD ["python", "app.py"]